# -*- coding: utf-8 -*-
"""Tarea1_Modificación_Librería.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1x1gF9tmbVn2MEHoZ8JH-AOrCRszGd15j

<div style="background-color:#e6f2ff; padding:20px; border-radius:10px;">
<img style="float:left; margin-right:20px;" src='Figures/alinco.png' width="120"/>
<h1 style="color:#000047;">Tarea 1: Modificación de la librería de clase</h1>
<br style="clear:both"/>
</div>

<div style="border-left:4px solid #000047; padding:10px; margin-top:10px; background:#f5f5f5;">
<b>Objetivo:</b> Construir la librería de la clase con el objetivo de organizar código funciones y clases útilies durante el proceso del curso.
</div>

Tomando en cuenta la libreria creada en clase `HyAIA`, y la función de reporte de calidad de datos `dqr()`, realizar lo siguiente:

Modificar la función `dqr()` para tener lo siguiente:

**1.- Modificar la función dqr() para que en el reporte se agregue una columna que sea booleana boolena para representar si una columna es categórica ('Is_categorical') ('Is_categorical' True-->col categorica, False ---> numérica)**
"""

import pandas as pd

def dqr(df: pd.DataFrame) -> pd.DataFrame:
    """
    Genera un reporte de calidad de datos para un DataFrame.
    Incluye información sobre tipo de dato, valores únicos, nulos y si es categórica.
    """
    report = pd.DataFrame({
        'Column': df.columns,
        'DataType': [df[col].dtype for col in df.columns],
        'UniqueValues': [df[col].nunique() for col in df.columns],
        'MissingValues': [df[col].isnull().sum() for col in df.columns],
        'MissingPercent': [round(df[col].isnull().mean() * 100, 2) for col in df.columns],
        'Is_categorical': [df[col].dtype == 'object' or str(df[col].dtype) == 'category' for col in df.columns]
    })
    return report

data = {
    'Nombre': ['Ana', 'Luis', 'Ana', None],
    'Edad': [23, 35, None, 40],
    'Ciudad': ['Qro', 'CDMX', 'Qro', 'MTY']
}

df = pd.DataFrame(data)
print(dqr(df))

"""**2.- Modificar la función dqr() para que en el reporte se agregue una columna con las categorías de las columnas (valores unicos) que resulten ser categóricas (si las categorias > 10, no agregar esas categorias)**

"""

import pandas as pd

def dqr(df: pd.DataFrame) -> pd.DataFrame:
    """
    Genera un reporte de calidad de datos para un DataFrame.
    Incluye tipo de dato, valores únicos, nulos, si es categórica y sus categorías (si <= 10).
    """
    report_data = []

    for col in df.columns:
        dtype = df[col].dtype
        unique_vals = df[col].nunique()
        missing_vals = df[col].isnull().sum()
        missing_pct = round(df[col].isnull().mean() * 100, 2)
        is_categorical = dtype == 'object' or str(dtype) == 'category'


        if is_categorical and unique_vals <= 10:
            categories = list(df[col].dropna().unique())
        elif is_categorical and unique_vals > 10:
            categories = "Más de 10 categorías"
        else:
            categories = None

        report_data.append({
            'Column': col,
            'DataType': dtype,
            'UniqueValues': unique_vals,
            'MissingValues': missing_vals,
            'MissingPercent': missing_pct,
            'Is_categorical': is_categorical,
            'Categories': categories
        })

    return pd.DataFrame(report_data)

data = {
    'Nombre': ['Ana', 'Luis', 'Ana', None],
    'Edad': [23, 35, None, 40],
    'Ciudad': ['Qro', 'CDMX', 'Qro', 'MTY'],
    'Color': ['Rojo', 'Azul', 'Verde', 'Rojo']
}

df = pd.DataFrame(data)
print(dqr(df))

"""**3.- Aplicar el análisis estadístico de las columnas creadas (max, min, mean, std) solo para las columnas que sean numéricas ('Is_categorical' == False)**

"""

import pandas as pd
import numpy as np
from pandas.api.types import is_numeric_dtype, is_bool_dtype

def dqr(df: pd.DataFrame, include_bool_as_categorical: bool = True) -> pd.DataFrame:
    """
    Genera un reporte de calidad de datos para un DataFrame.

    Parámetros
    ----------
    df : pd.DataFrame
        DataFrame de entrada.
    include_bool_as_categorical : bool
        Si True, las columnas booleanas se consideran categóricas.

    Devuelve
    --------
    pd.DataFrame
        Reporte con:
        - Column, DataType, UniqueValues, MissingValues, MissingPercent
        - Is_categorical
        - Categories (si Is_categorical y <= 10 categorías)
        - Num_Min, Num_Max, Num_Mean, Num_Std (solo para numéricas)
    """
    report_rows = []

    for col in df.columns:
        s = df[col]
        dtype = s.dtype

        is_category_dtype = isinstance(dtype, pd.CategoricalDtype)
        is_object_dtype = dtype == 'object'
        is_bool = is_bool_dtype(dtype)

        is_categorical = is_object_dtype or is_category_dtype or (include_bool_as_categorical and is_bool)

        unique_vals = s.nunique(dropna=True)
        missing_vals = s.isna().sum()
        missing_pct = round((missing_vals / len(s)) * 100, 2) if len(s) > 0 else 0.0

   )
        if is_categorical:
            if unique_vals <= 10:
                # Lista de categorías sin NaN; pd.unique preserva orden de aparición
                categories = list(pd.unique(s.dropna()))
            else:
                categories = "Más de 10 categorías"
        else:
            categories = None


        if (not is_categorical) and is_numeric_dtype(dtype):
            num_min = s.min(skipna=True)
            num_max = s.max(skipna=True)
            num_mean = s.mean(skipna=True)
            num_std = s.std(skipna=True)
        else:
            num_min = num_max = num_mean = num_std = np.nan

        report_rows.append({
            'Column': col,
            'DataType': dtype,
            'UniqueValues': unique_vals,
            'MissingValues': missing_vals,
            'MissingPercent': missing_pct,
            'Is_categorical': is_categorical,
            'Categories': categories,
            'Num_Min': num_min,
            'Num_Max': num_max,
            'Num_Mean': num_mean,
            'Num_Std': num_std
        })

    report = pd.DataFrame(report_rows)


    ordered_cols = [
        'Column', 'DataType', 'UniqueValues', 'MissingValues', 'MissingPercent',
        'Is_categorical', 'Categories',
        'Num_Min', 'Num_Max', 'Num_Mean', 'Num_Std'
    ]
    return report[ordered_cols]

data = {
    'Nombre': ['Ana', 'Luis', 'Ana', None],
    'Edad': [23, 35, None, 40],
    'Ingreso': [10500.5, 22000, 18000, None],
    'Ciudad': ['Qro', 'CDMX', 'Qro', 'MTY'],
    'Color': ['Rojo', 'Azul', 'Verde', 'Rojo']
}

df = pd.DataFrame(data)
reporte = dqr(df)
print(reporte)